name: Test_HONUAE

on: 
  push:
    branches:
      - main
  
jobs:
  test:
    name: Run tests with Python 3.13
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'
      - run: python --version
      - run: python -m pip install -r requirements.txt
      - run: pytest
      